<Feature: Postprocessing>
PvB-Groep-1/DevDorp pull request #78
Opened 2020-05-12 15:37 UTC by SharonaVorswijk

Add Post processing to the camera

2020-05-13 07:43 UTC, waffel183 commented
When placing a building, the building appears without material.
![image](https://user-images.githubusercontent.com/15922303/81785005-05e94880-94fe-11ea-8ba4-9b91ce6ca366.png)

Also the entire world is a lot darker than previously, don't know if this is intended.

2020-05-13 07:43 UTC, waffel183 requested changes
Fix material on creating new building.
(Possibly) Fix dark world.

2020-05-13 07:44 UTC, waffel183 commented
Also pull the development branch to the feature branch before creating a pull request to fix the merge conflicts.

2020-05-25 23:22 UTC, projojoboy submitted a review, later dismissed

2020-05-26 12:25 UTC, closed without merging